### ISSUE TITLE
Occasional error in createContext with code BAD_CONFIG

### ISSUE THREAD

**Issue by dooreelko** [markfguerra/GLWallpaperService#22]
Some of my users have this crash and 1. I can't reproduce it myself and 2. can't imagine how this is even possible - we're choosing from available configs and returning the closest one.

Here's the stack trace even though not really helpful (i slightly modified sources hoping to get better insight):
java.lang.RuntimeException: java.lang.RuntimeException: createContext failed: 12293
at net.rbgrn.android.glwallpaperservice.GLThread.run(GLWallpaperService.java:498)
Caused by: java.lang.RuntimeException: createContext failed: 12293
at net.rbgrn.android.glwallpaperservice.EglHelper.throwEglException(GLWallpaperService.java:422)
at net.rbgrn.android.glwallpaperservice.EglHelper.start(GLWallpaperService.java:327)
at net.rbgrn.android.glwallpaperservice.GLThread.guardedRun(GLWallpaperService.java:564)
at net.rbgrn.android.glwallpaperservice.GLThread.run(GLWallpaperService.java:489)

ideas?

**Comment by dooreelko** [comment]
And even it doesn't directly correlates, i'm creating 2.0 surface and i don't know on what device it's failing.

**Comment by markfguerra** [comment]
This issue is being closed because the project is being moved to the [GLWallpaperService GitHub organization](https://github.com/GLWallpaperService/GLWallpaperService)

If you're still having this problem, please go there and open new issue or pull request. Don't forget to link back to this page.
